# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: resonite-love.RESOLauncher
PackageVersion: 1.11.1
PackageLocale: en-US
Publisher: resonite.love community
PublisherUrl: https://resonite.love/
PublisherSupportUrl: https://github.com/resonite-love/launcher/issues
PackageName: RESO Launcher
PackageUrl: https://github.com/resonite-love/launcher
License: MIT
LicenseUrl: https://github.com/resonite-love/launcher/blob/v1.11.1/LICENSE
ShortDescription: A community launcher for installing, updating, and managing Resonite profiles.
ReleaseNotesUrl: https://github.com/resonite-love/launcher/releases/tag/v1.11.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
